import { StyleSheet, StatusBar, Dimensions } from 'react-native';

const{width, height} = Dimensions.get('window');
const statusBarHeight = StatusBar.currentHeight || 0;

const Styles = StyleSheet.create({
  // backgroundImage: {
  //   resizeMode:'cover',
  //   height:'100%',
  // },
  container: {
    height:'100%',
    flexWrap: 'wrap',
    flexDirection: 'column',
    alignItems: 'center',
    backgroundColor: '#0A0914',
    marginBottom:0,
  },
  Header: {
    height: 50,
    width: '100%',
    backgroundColor: 'transparent',
    marginTop: statusBarHeight,
    justifyContent: 'center',
    alignItems: 'flex-start',
  },
  AppName: {
    width: '60%',
    height: 50,
    resizeMode: 'cover',
    marginLeft: 10,
    marginTop: 7,
  },
  taskContainer:{
    flex:1,
    width:width,
    maxHeight:height,
  },
  listas: {
    width: width - 20,
    minHeight: 50,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    textAlign: 'center',
    marginLeft: 5,
    marginRight: 5,
    padding: 0,
    backgroundColor: '#0C1623',
    color: '#fff',
    borderRadius: 5,
    marginBottom: 5,
  },
  ListDescription: {
    flex: 0.8,
    textAlign: 'left',
    paddingLeft: 1,
    maxWidth: '95%',
    margin: 8,
    color: '#fff',
  },
  ListStatus: {
    flex: 0.1,
  },
  IconLogOut: {
    position: 'absolute',
    top: 12,
    right: 5,
    color: 'rgb(186, 6, 29)',
    fontSize: 25,
    padding: 5,
  },
  IconTrash: {
    color: 'rgb(186, 6, 29)',
    fontSize: 25,
  },
  IconAddTasksContainer: {
    position: 'absolute',
    bottom: 20,
    width: 50,
    height: 50,
    right: 20,
    borderRadius: 5,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgb(201, 197, 198)',
    borderWidth: 1,
  },
  IconAddTasks: {
    color: 'blue',
    fontSize: 25,
    padding: 12,
  },
  IconCheck: {
    fontSize: 25,
    padding: 10,
  },
  Modalback: {
    backgroundColor: 'rgba(10, 9, 20, 0.97)',
    width: '100%',
    height: '100%',
  },
  Boxaddtask: {
    position: 'absolute',
    width: '80%',
    height: '70%',
    bottom: 50,
    top: 50,
    backgroundColor: '#0C1623',
    margin: 'auto',
    alignSelf: 'center',
  },
  btnaddtask: {
    minWidth: '30%',
    height: 'auto',
    backgroundColor: 'rgb(53, 53, 61)',
    color: 'white',
    padding: 10,
    margin: 10,
    justifyContent:'center',
    alignContent:'center',
    borderRadius: 5,
  },
  boxBtn: {
    flexDirection: 'row',
    width: '100%',
    height: 'auto',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderRadius: 5,
    backgroundColor: '#0C1623',
  },
  BoxTxt: {
    width: '90%',
    height: '100%',
    color: 'white',
    borderColor: 'rgb(53, 53, 61)',
    borderWidth: 0,
    borderRadius: 5,
    textAlign: 'left',
    textAlignVertical: 'top',
    padding: 10,
    margin: 'auto',
  },
  DelContainer: {
    position: 'absolute',
    width: '80%',
    height: '20%',
    backgroundColor: 'rgba(12, 22, 35, 0.6)',
    alignSelf: 'center',
    bottom: 50,
    top: 50,
    margin:'auto',
    justifyContent: 'center',
    alignContent: 'center',
    textAlign: 'center',
    borderRadius: 5,
  },
  iconsDelete: {
    width: '100%',
    height: 'auto',
    justifyContent: 'space-around',
    flexDirection: 'row',
    margin: 0,
    padding: 0,
  },
  touchdelicon: {
    width: 'auto',
    minWidth: '15%',
    height: 'auto',
    justifyContent: 'center',
    alignContent: 'center',
  },
  delIcons: {
    width: 'auto',
    height: 'auto',
    fontSize: 30,
    padding: 5,
    margin: 5,
    borderWidth: 0,
    borderRadius: 5,
    margin: 'auto',
  },
  imgLoginContainer: {
    width: '100%',
    height: 'auto',
    justifyContent: 'center',
    alignContent: 'center',
    textAlign: 'center',
    marginTop: '15%',
  },
  imgLogin: {
    width: '60%',
    height: 50,
    resizeMode: 'cover',
    margin: 'auto',
    alignSelf:'center',
  },
  loginContainer: {
    width: '80%',
    height: 'auto',
    backgroundColor: '#0C1623',
    margin: 'auto',
    marginBottom: 0,
    padding: 0,
    marginTop: 30,
    borderRadius: 5,
  },
  btnWindowsLoginContainer: {
    width: '100%',
    height:'10%',
    flexDirection: 'row',
    backgroundColor: 'transparent',
    justifyContent:'center',
    alignContent:'center',
    margin: 'auto',
    marginTop: 0,
    marginBottom: 0,
    padding: 0,
    borderRadius:5,
  },
  btnLogin: {
    width: '50%',
    height: '100%',
    margin: 'auto',
    justifyContent:'center',
    borderRadius:5,
  },
  TxtBtn: {
    margin: 'auto',
    fontSize: 18,
    color: 'white',
    alignSelf:'center',
    
  },
  FormContainer: {
    flexDirection: 'column',
    justifyContent: 'center',
    marginTop: '10%',
  },
  InputsForm: {
    width: '90%',
    height: 40,
    backgroundColor: 'transparent',
    color: 'white',
    margin: 10,
    marginBottom: 0,
    borderRadius: 5,
    padding: 10,
    borderWidth: 3,
    borderColor: '#0A0914',
  },
  BtnForms: {
    width: '30%',
    alignSelf: 'center',
    padding: 5,
    color: '#000',
    backgroundColor: '#fff',
    marginTop:30,
    borderRadius: 5,
  },
  txtBtnLogin:{
    alignSelf:'center',
    fontSize:18,
    padding:5,
  },
  txtWarning: {
    fontSize: 15,
    color: 'red',
    paddingLeft: 15,
    marginTop:15,
  },
  loginIcons: {
    flexDirection: 'row',
    marginTop: 0,
    justifyContent: 'center',
    marginTop:15,
  },
  icons: {
    margin: 0,
    padding: 10,
  },
  versionTxt: {
    position: 'absolute',
    bottom: 5,
    right: 5,
    color: 'grey',
    fontSize: 15,
  },
});

export default Styles;
